### ISSUE TITLE
PXN: procedura končí chybou

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#438]
Dobrý den,

zkusil jsem dnes spustit 2x proceduru pro PXN žádosti, ale ani jednou nedoběhla správně. 

```log
Jul 08, 2022 11:08:00 AM cz.inovatika.sdnnt.sched.Job fire
INFO: Job krameriove_kontrola_zaznamu fired
Jul 08, 2022 11:08:00 AM cz.inovatika.sdnnt.sched.Job fire
INFO: Job zadost_po_minute fired
Jul 08, 2022 11:08:00 AM cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl check
INFO: Initializing px process
Jul 08, 2022 11:08:00 AM cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl check
INFO: Current iteration filter [id_pid:uuid, fmt:BK, dntstav:(A OR PA OR NL)]
Jul 08, 2022 11:08:00 AM cz.inovatika.sdnnt.index.IterationSupport iterate
INFO: Iteration rows 1000
Jul 08, 2022 11:08:25 AM cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl check
INFO: Found candidates: 149550
Jul 08, 2022 11:08:33 AM cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl check
INFO: Found candidates after used check: 147150
Jul 08, 2022 11:09:00 AM cz.inovatika.sdnnt.sched.Job fire
INFO: Job zadost_po_minute fired
Jul 08, 2022 11:09:52 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl closeRequest
INFO: Deadline for zadost Fri Jul 08 11:14:52 CEST 2022
Jul 08, 2022 11:10:00 AM cz.inovatika.sdnnt.sched.Job fire
INFO: Job zadost_po_minute fired
Jul 08, 2022 11:11:00 AM cz.inovatika.sdnnt.sched.Job fire
INFO: Job zadost_po_minute fired
Jul 08, 2022 11:11:39 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl closeRequest
INFO: Deadline for zadost null
Jul 08, 2022 11:11:47 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:47 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:47 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:47 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:47 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:47 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:47 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:48 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:48 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:48 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:48 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:48 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:48 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:48 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:48 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:48 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:48 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:48 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:48 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:48 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl curatorSwitchState
INFO: Processing zadost id fec1d9d2-54a2-4f71-bff6-c5a5ec407d28
Jul 08, 2022 11:11:50 AM cz.inovatika.sdnnt.services.impl.AccountServiceImpl closeRequest
INFO: Deadline for zadost null
Jul 08, 2022 11:11:56 AM cz.inovatika.sdnnt.AccountServlet$Actions$8 doPerform
SEVERE: null
cz.inovatika.sdnnt.services.exceptions.ConflictException: Konflikt, nejde uloit, ádost byla zmìnìna
        at cz.inovatika.sdnnt.services.impl.AccountServiceImpl.saveRequest(AccountServiceImpl.java:231)
        at cz.inovatika.sdnnt.services.impl.AccountServiceImpl.saveCuratorRequest(AccountServiceImpl.java:198)
        at cz.inovatika.sdnnt.AccountServlet$Actions$8.doPerform(AccountServlet.java:455)
        at cz.inovatika.sdnnt.AccountServlet.processRequest(AccountServlet.java:83)
        at cz.inovatika.sdnnt.AccountServlet.doPost(AccountServlet.java:142)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:64)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:710)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:457)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
        at cz.inovatika.sdnnt.ApiServlet.processRequest(ApiServlet.java:30)
        at cz.inovatika.sdnnt.ApiServlet.doPost(ApiServlet.java:60)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at cz.inovatika.sdnnt.tracking.TrackingFilter.doFilter(TrackingFilter.java:81)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at cz.inovatika.sdnnt.openapi.endpoints.api.ApiOriginFilter.doFilter(ApiOriginFilter.java:15)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at cz.inovatika.sdnnt.services.impl.shib.ShibbolethFilter.doFilter(ShibbolethFilter.java:109)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)

Jul 08, 2022 11:12:00 AM cz.inovatika.sdnnt.sched.Job fire
INFO: Job zadost_po_minute fired
Jul 08, 2022 11:13:00 AM cz.inovatika.sdnnt.sched.Job fire
INFO: Job zadost_po_minute fired
```

```json
"krameriove_kontrola_zaznamu":{
	"type":"kramerius_px_check",
	"cron":"0 8 11 8 * ? *",
	"iteration":{
		"states":["A","PA","NL"]
	},
	"results":{
		"request":{
			"items":60,
			"type":"PXN"
		}
	}
},
```

@Cypzirschova

**Comment by pavel-stastny** [comment]
@smallcubes Uvedená výjimka nesouvisí s procesem.  Jedná se o konflikt při ukládání žádosti.  PXN pouze nedoběhl (byl proveden restart tomcatu).  Změnil jsem defaultní timeouty pro spojení (na DEVu a na TESTu) a vyzkoušel na DEVu.... Vyzkoušejte, prosím, na testu.

**Comment by smallcubes** [comment]
Problém byl v dlouhém resolvování DNS jmen. Děkuji @pavel-stastny za navedení.
